// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import PagyController from "./pagy_controller"
application.register("pagy-initializer", PagyController)

import Notification from "./notification_controller"
application.register("notification", Notification)
