version: "3.4"

services:
  ruby:
    build:
      context: .
      target: app_ruby_dev
    depends_on:
      - postgis
      - redis
    env_file:
      - '.env.development'
    ports:
      - "3000:3000"

  postgis:
    image: postgis/postgis:13-3.3-alpine
    networks:
      - backend
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: postgis
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - '.env.development'

  redis:
    image: redis:alpine
    command: redis-server
    container_name: redis
    networks:
      - backend
    ports:
      - "6379:6379"

volumes:
  db_data:
