require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/test_articles", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # TestArticle. As you add validations to TestArticle, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TestArticle.create! valid_attributes
      get test_articles_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      test_article = TestArticle.create! valid_attributes
      get test_article_url(test_article)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_test_article_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      test_article = TestArticle.create! valid_attributes
      get edit_test_article_url(test_article)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TestArticle" do
        expect {
          post test_articles_url, params: { test_article: valid_attributes }
        }.to change(TestArticle, :count).by(1)
      end

      it "redirects to the created test_article" do
        post test_articles_url, params: { test_article: valid_attributes }
        expect(response).to redirect_to(test_article_url(TestArticle.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TestArticle" do
        expect {
          post test_articles_url, params: { test_article: invalid_attributes }
        }.to change(TestArticle, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post test_articles_url, params: { test_article: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested test_article" do
        test_article = TestArticle.create! valid_attributes
        patch test_article_url(test_article), params: { test_article: new_attributes }
        test_article.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the test_article" do
        test_article = TestArticle.create! valid_attributes
        patch test_article_url(test_article), params: { test_article: new_attributes }
        test_article.reload
        expect(response).to redirect_to(test_article_url(test_article))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        test_article = TestArticle.create! valid_attributes
        patch test_article_url(test_article), params: { test_article: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested test_article" do
      test_article = TestArticle.create! valid_attributes
      expect {
        delete test_article_url(test_article)
      }.to change(TestArticle, :count).by(-1)
    end

    it "redirects to the test_articles list" do
      test_article = TestArticle.create! valid_attributes
      delete test_article_url(test_article)
      expect(response).to redirect_to(test_articles_url)
    end
  end
end
