require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/test_posts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # TestPost. As you add validations to TestPost, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TestPost.create! valid_attributes
      get test_posts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      test_post = TestPost.create! valid_attributes
      get test_post_url(test_post)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_test_post_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      test_post = TestPost.create! valid_attributes
      get edit_test_post_url(test_post)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TestPost" do
        expect {
          post test_posts_url, params: { test_post: valid_attributes }
        }.to change(TestPost, :count).by(1)
      end

      it "redirects to the created test_post" do
        post test_posts_url, params: { test_post: valid_attributes }
        expect(response).to redirect_to(test_post_url(TestPost.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TestPost" do
        expect {
          post test_posts_url, params: { test_post: invalid_attributes }
        }.to change(TestPost, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post test_posts_url, params: { test_post: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested test_post" do
        test_post = TestPost.create! valid_attributes
        patch test_post_url(test_post), params: { test_post: new_attributes }
        test_post.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the test_post" do
        test_post = TestPost.create! valid_attributes
        patch test_post_url(test_post), params: { test_post: new_attributes }
        test_post.reload
        expect(response).to redirect_to(test_post_url(test_post))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        test_post = TestPost.create! valid_attributes
        patch test_post_url(test_post), params: { test_post: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested test_post" do
      test_post = TestPost.create! valid_attributes
      expect {
        delete test_post_url(test_post)
      }.to change(TestPost, :count).by(-1)
    end

    it "redirects to the test_posts list" do
      test_post = TestPost.create! valid_attributes
      delete test_post_url(test_post)
      expect(response).to redirect_to(test_posts_url)
    end
  end
end
