require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe('/aim/core/groups', type: :request) do
  # This should return the minimal set of attributes required to create a valid
  # Aim::Core::Group. As you add validations to Aim::Core::Group, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Aim::Core::Group.create!(valid_attributes)
      get aim_core_groups_url
      expect(response).to(be_successful)
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      group = Aim::Core::Group.create!(valid_attributes)
      get aim_core_group_url(group)
      expect(response).to(be_successful)
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_aim_core_group_url
      expect(response).to(be_successful)
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      group = Aim::Core::Group.create!(valid_attributes)
      get edit_aim_core_group_url(group)
      expect(response).to(be_successful)
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Aim::Core::Group' do
        expect do
          post(aim_core_groups_url, params: { aim_core_group: valid_attributes }, as: :json)
        end.to(change(Aim::Core::Group, :count).by(1))
      end

      it 'redirects to the created aim_core_group' do
        post aim_core_groups_url, params: { aim_core_group: valid_attributes }, as: :json
        expect(response).to(redirect_to(aim_core_group_url(Aim::Core::Group.last)))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Aim::Core::Group' do
        expect do
          post(aim_core_groups_url, params: { aim_core_group: invalid_attributes }, as: :json)
        end.to(change(Aim::Core::Group, :count).by(0))
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post aim_core_groups_url, params: { aim_core_group: invalid_attributes }, as: :json
        expect(response).to(have_http_status(:unprocessable_entity))
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested aim_core_group' do
        group = Aim::Core::Group.create!(valid_attributes)
        patch aim_core_group_url(group), params: { aim_core_group: new_attributes }, as: :json
        group.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the aim_core_group' do
        group = Aim::Core::Group.create!(valid_attributes)
        patch aim_core_group_url(group), params: { aim_core_group: new_attributes }, as: :json
        group.reload
        expect(response).to(redirect_to(aim_core_group_url(group)))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        group = Aim::Core::Group.create!(valid_attributes)
        patch aim_core_group_url(group), params: { aim_core_group: invalid_attributes }, as: :json
        expect(response).to(have_http_status(:unprocessable_entity))
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested aim_core_group' do
      group = Aim::Core::Group.create!(valid_attributes)
      expect do
        delete(aim_core_group_url(group))
      end.to(change(Aim::Core::Group, :count).by(-1))
    end

    it 'redirects to the aim_core_groups list' do
      group = Aim::Core::Group.create!(valid_attributes)
      delete aim_core_group_url(group)
      expect(response).to(redirect_to(aim_core_groups_url))
    end
  end
end
