require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/aim/authorization/group_requests", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Aim::Authorization::GroupRequest. As you add validations to Aim::Authorization::GroupRequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Aim::Authorization::GroupRequest.create! valid_attributes
      get aim_authorization_group_requests_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      group_request = Aim::Authorization::GroupRequest.create! valid_attributes
      get aim_authorization_group_request_url(group_request)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_aim_authorization_group_request_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      group_request = Aim::Authorization::GroupRequest.create! valid_attributes
      get edit_aim_authorization_group_request_url(group_request)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Aim::Authorization::GroupRequest" do
        expect {
          post aim_authorization_group_requests_url, params: { aim_authorization_group_request: valid_attributes }
        }.to change(Aim::Authorization::GroupRequest, :count).by(1)
      end

      it "redirects to the created aim_authorization_group_request" do
        post aim_authorization_group_requests_url, params: { aim_authorization_group_request: valid_attributes }
        expect(response).to redirect_to(aim_authorization_group_request_url(Aim::Authorization::GroupRequest.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Aim::Authorization::GroupRequest" do
        expect {
          post aim_authorization_group_requests_url, params: { aim_authorization_group_request: invalid_attributes }
        }.to change(Aim::Authorization::GroupRequest, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post aim_authorization_group_requests_url, params: { aim_authorization_group_request: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested aim_authorization_group_request" do
        group_request = Aim::Authorization::GroupRequest.create! valid_attributes
        patch aim_authorization_group_request_url(group_request), params: { aim_authorization_group_request: new_attributes }
        group_request.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the aim_authorization_group_request" do
        group_request = Aim::Authorization::GroupRequest.create! valid_attributes
        patch aim_authorization_group_request_url(group_request), params: { aim_authorization_group_request: new_attributes }
        group_request.reload
        expect(response).to redirect_to(aim_authorization_group_request_url(group_request))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        group_request = Aim::Authorization::GroupRequest.create! valid_attributes
        patch aim_authorization_group_request_url(group_request), params: { aim_authorization_group_request: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested aim_authorization_group_request" do
      group_request = Aim::Authorization::GroupRequest.create! valid_attributes
      expect {
        delete aim_authorization_group_request_url(group_request)
      }.to change(Aim::Authorization::GroupRequest, :count).by(-1)
    end

    it "redirects to the aim_authorization_group_requests list" do
      group_request = Aim::Authorization::GroupRequest.create! valid_attributes
      delete aim_authorization_group_request_url(group_request)
      expect(response).to redirect_to(aim_authorization_group_requests_url)
    end
  end
end
