require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/authorization/map_group_requests", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Authorization::MapGroupRequest. As you add validations to Authorization::MapGroupRequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Authorization::MapGroupRequest.create! valid_attributes
      get authorization_map_group_requests_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      map_group_request = Authorization::MapGroupRequest.create! valid_attributes
      get authorization_map_group_request_url(map_group_request)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_authorization_map_group_request_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      map_group_request = Authorization::MapGroupRequest.create! valid_attributes
      get edit_authorization_map_group_request_url(map_group_request)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Authorization::MapGroupRequest" do
        expect {
          post authorization_map_group_requests_url, params: { authorization_map_group_request: valid_attributes }
        }.to change(Authorization::MapGroupRequest, :count).by(1)
      end

      it "redirects to the created authorization_map_group_request" do
        post authorization_map_group_requests_url, params: { authorization_map_group_request: valid_attributes }
        expect(response).to redirect_to(authorization_map_group_request_url(Authorization::MapGroupRequest.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Authorization::MapGroupRequest" do
        expect {
          post authorization_map_group_requests_url, params: { authorization_map_group_request: invalid_attributes }
        }.to change(Authorization::MapGroupRequest, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post authorization_map_group_requests_url, params: { authorization_map_group_request: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested authorization_map_group_request" do
        map_group_request = Authorization::MapGroupRequest.create! valid_attributes
        patch authorization_map_group_request_url(map_group_request), params: { authorization_map_group_request: new_attributes }
        map_group_request.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the authorization_map_group_request" do
        map_group_request = Authorization::MapGroupRequest.create! valid_attributes
        patch authorization_map_group_request_url(map_group_request), params: { authorization_map_group_request: new_attributes }
        map_group_request.reload
        expect(response).to redirect_to(authorization_map_group_request_url(map_group_request))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        map_group_request = Authorization::MapGroupRequest.create! valid_attributes
        patch authorization_map_group_request_url(map_group_request), params: { authorization_map_group_request: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested authorization_map_group_request" do
      map_group_request = Authorization::MapGroupRequest.create! valid_attributes
      expect {
        delete authorization_map_group_request_url(map_group_request)
      }.to change(Authorization::MapGroupRequest, :count).by(-1)
    end

    it "redirects to the authorization_map_group_requests list" do
      map_group_request = Authorization::MapGroupRequest.create! valid_attributes
      delete authorization_map_group_request_url(map_group_request)
      expect(response).to redirect_to(authorization_map_group_requests_url)
    end
  end
end
