require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/authorization/request_workerable_workers", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Authorization::RequestWorkerableWorker. As you add validations to Authorization::RequestWorkerableWorker, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Authorization::RequestWorkerableWorker.create! valid_attributes
      get authorization_request_workerable_workers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      request_workerable_worker = Authorization::RequestWorkerableWorker.create! valid_attributes
      get authorization_request_workerable_worker_url(request_workerable_worker)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_authorization_request_workerable_worker_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      request_workerable_worker = Authorization::RequestWorkerableWorker.create! valid_attributes
      get edit_authorization_request_workerable_worker_url(request_workerable_worker)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Authorization::RequestWorkerableWorker" do
        expect {
          post authorization_request_workerable_workers_url, params: { authorization_request_workerable_worker: valid_attributes }
        }.to change(Authorization::RequestWorkerableWorker, :count).by(1)
      end

      it "redirects to the created authorization_request_workerable_worker" do
        post authorization_request_workerable_workers_url, params: { authorization_request_workerable_worker: valid_attributes }
        expect(response).to redirect_to(authorization_request_workerable_worker_url(Authorization::RequestWorkerableWorker.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Authorization::RequestWorkerableWorker" do
        expect {
          post authorization_request_workerable_workers_url, params: { authorization_request_workerable_worker: invalid_attributes }
        }.to change(Authorization::RequestWorkerableWorker, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post authorization_request_workerable_workers_url, params: { authorization_request_workerable_worker: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested authorization_request_workerable_worker" do
        request_workerable_worker = Authorization::RequestWorkerableWorker.create! valid_attributes
        patch authorization_request_workerable_worker_url(request_workerable_worker), params: { authorization_request_workerable_worker: new_attributes }
        request_workerable_worker.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the authorization_request_workerable_worker" do
        request_workerable_worker = Authorization::RequestWorkerableWorker.create! valid_attributes
        patch authorization_request_workerable_worker_url(request_workerable_worker), params: { authorization_request_workerable_worker: new_attributes }
        request_workerable_worker.reload
        expect(response).to redirect_to(authorization_request_workerable_worker_url(request_workerable_worker))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        request_workerable_worker = Authorization::RequestWorkerableWorker.create! valid_attributes
        patch authorization_request_workerable_worker_url(request_workerable_worker), params: { authorization_request_workerable_worker: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested authorization_request_workerable_worker" do
      request_workerable_worker = Authorization::RequestWorkerableWorker.create! valid_attributes
      expect {
        delete authorization_request_workerable_worker_url(request_workerable_worker)
      }.to change(Authorization::RequestWorkerableWorker, :count).by(-1)
    end

    it "redirects to the authorization_request_workerable_workers list" do
      request_workerable_worker = Authorization::RequestWorkerableWorker.create! valid_attributes
      delete authorization_request_workerable_worker_url(request_workerable_worker)
      expect(response).to redirect_to(authorization_request_workerable_workers_url)
    end
  end
end
