require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/authorization/scanned_frames", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Authorization::ScannedFrame. As you add validations to Authorization::ScannedFrame, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Authorization::ScannedFrame.create! valid_attributes
      get authorization_scanned_frames_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      scanned_frame = Authorization::ScannedFrame.create! valid_attributes
      get authorization_scanned_frame_url(scanned_frame)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_authorization_scanned_frame_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      scanned_frame = Authorization::ScannedFrame.create! valid_attributes
      get edit_authorization_scanned_frame_url(scanned_frame)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Authorization::ScannedFrame" do
        expect {
          post authorization_scanned_frames_url, params: { authorization_scanned_frame: valid_attributes }
        }.to change(Authorization::ScannedFrame, :count).by(1)
      end

      it "redirects to the created authorization_scanned_frame" do
        post authorization_scanned_frames_url, params: { authorization_scanned_frame: valid_attributes }
        expect(response).to redirect_to(authorization_scanned_frame_url(Authorization::ScannedFrame.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Authorization::ScannedFrame" do
        expect {
          post authorization_scanned_frames_url, params: { authorization_scanned_frame: invalid_attributes }
        }.to change(Authorization::ScannedFrame, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post authorization_scanned_frames_url, params: { authorization_scanned_frame: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested authorization_scanned_frame" do
        scanned_frame = Authorization::ScannedFrame.create! valid_attributes
        patch authorization_scanned_frame_url(scanned_frame), params: { authorization_scanned_frame: new_attributes }
        scanned_frame.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the authorization_scanned_frame" do
        scanned_frame = Authorization::ScannedFrame.create! valid_attributes
        patch authorization_scanned_frame_url(scanned_frame), params: { authorization_scanned_frame: new_attributes }
        scanned_frame.reload
        expect(response).to redirect_to(authorization_scanned_frame_url(scanned_frame))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        scanned_frame = Authorization::ScannedFrame.create! valid_attributes
        patch authorization_scanned_frame_url(scanned_frame), params: { authorization_scanned_frame: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested authorization_scanned_frame" do
      scanned_frame = Authorization::ScannedFrame.create! valid_attributes
      expect {
        delete authorization_scanned_frame_url(scanned_frame)
      }.to change(Authorization::ScannedFrame, :count).by(-1)
    end

    it "redirects to the authorization_scanned_frames list" do
      scanned_frame = Authorization::ScannedFrame.create! valid_attributes
      delete authorization_scanned_frame_url(scanned_frame)
      expect(response).to redirect_to(authorization_scanned_frames_url)
    end
  end
end
